Update patch set 1
Patch Set 1: Code-Review-1

Apologies, the nova change that depends on this is still failing with the following:

https://storage.bhs.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_2bf/795533/2/check/requirements-check/2bf67e2/job-output.txt

ERROR: Package 'types-paramiko' is used in test-requirements.txt but not in lower-constraints.txt

Patch-set: 1
Label: Code-Review=-1