Blacklist sphinx 3.4.2 because of Flask regressions
Using sphinx version 3.4.2 with Flask and documentation builds results
in an error:

  Exception occurred:
    File "/opt/stack/keystone/.tox/docs/lib/python3.8/site-packages/flask/globals.py", line 38, in _lookup_req_object
      raise RuntimeError(_request_ctx_err_msg)
  RuntimeError: Working outside of request context.

This issue has occured a few times with sphinx in the past and has been
reported upstream [0][1].

This commit blacklists sphinx 3.4.2 until we get a newer release with a fix.

[0] https://github.com/sphinx-doc/sphinx/issues/8655
[1] https://github.com/sphinx-doc/sphinx/issues/2796

Change-Id: Ie80e45571efafe73a553ddd89c5be90fe97bea4d