Update patch set 2
Patch Set 2:

Hmm okay so the py27 stuff works now but now we're falling over installing httpretty

 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)

http://logs.openstack.org/98/294398/2/check/gate-requirements-integration-dsvm/6797402/console.html#_2016-03-19_05_40_03_227

The strange thing in on OVH we install from wheel[1] rather then tar.gz[2] so I think something strange is going on behind the scenes.

Unless someone beats me to it I'll look at this next week.

[1] http://logs.openstack.org/47/282347/6/check/gate-requirements-integration-dsvm/cffee0e/console.html.gz#_2016-03-08_15_21_10_881
[2] http://logs.openstack.org/98/294398/2/check/gate-requirements-integration-dsvm/6797402/console.html#_2016-03-19_05_40_03_226

Patch-set: 2