Update patch set 3
Patch Set 3:

Looks like there is still a cap in osprofiler that needs to be removed:

```
ERROR: Cannot install -r /home/zuul/src/opendev.org/openstack/requirements/upper-constraints.txt (line 26) and prettytable===2.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested prettytable===2.0.0
    osprofiler 3.4.0 depends on PrettyTable<0.8 and >=0.7.2
```

Patch-set: 3