DNM revert libvirt-python upper-constraints bump to 6.8.0
Partial revert of change I1bc1fe988e3cfd4824dd7b4a9327a67db46c1533
suspected of breaking nova-compute with:

File "/usr/local/lib/python3.6/dist-packages/eventlet/tpool.py", line 149, in proxy_call
  if isinstance(rv, autowrap):
File "/usr/lib/python3.6/typing.py", line 1162, in __instancecheck__
return issubclass(instance.__class__, self)
File "/usr/lib/python3.6/typing.py", line 1148, in __subclasscheck__
  raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks

Change-Id: I5990b00f94305813780854698fef2d3e1e721e79