Update patch set 3
Patch Set 3:

this failure has nothing to do with anything:

File "/home/jenkins/workspace/gate-requirements-tox-py27-check-uc-ubuntu-xenial/.tox/py27-check-uc/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/jenkins/workspace/gate-requirements-tox-py27-check-uc-ubuntu-xenial/.tox/py27-check-uc/lib/python2.7/site-packages/pyparsing-2.1.10.dist-info/METADATA'


trying again, seems like build environment needs to be cleared and rebuilt

Patch-set: 3