DNM: Debugging change.
The stable/liberty branch is failing with:

 Collecting httpretty<0.8.7,>=0.8.4 (from -r /opt/stack/new/requirements/global-requirements.txt (line 267))
   Downloading http://mirror.gra1.ovh.openstack.org/pypi/packages/source/h/httpretty/httpretty-0.8.6.tar.gz (40kB)
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-tkc16u5k/httpretty/setup.py", line 86, in <module>
         version=read_version(),
       File "/tmp/pip-build-tkc16u5k/httpretty/setup.py", line 46, in read_version
         finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
       File "/tmp/pip-build-tkc16u5k/httpretty/setup.py", line 78, in <lambda>
         open(os.path.join(os.path.dirname(__file__), *f)).read()
       File "/tmp/tmp2n5Yww/lib/python3.4/encodings/ascii.py", line 26, in decode
         return codecs.ascii_decode(input, self.errors)[0]
     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)

I can't reproduce it outside the gate so this change is to reproduce it and
then try to debug it.

Related-Bug: 1560808
Depends-On: If9e8dfadb2ff160bb7c2b2993fab498a96a6906c
Change-Id: I1cea9763c0f547b5f2212b4943044136d11f8972