Update patch set 2
Patch Set 2:

I tried reproducing the issue, but instead ran into other problems with python2.7:
ERROR: glance-store 0.28.0 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: warlock 1.3.0 has requirement jsonschema<3,>=0.7, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: python-ironicclient 2.7.1 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: jaeger-client 4.0.0 has requirement tornado<5,>=4.3, but you'll have tornado 5.1.1 which is incompatible.
ERROR: taskflow 3.4.0 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: tempest 20.0.0 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: os-net-config 10.4.0 has requirement jsonschema<3.0.0,>=2.0.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: python-designateclient 2.11.0 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
ERROR: botocore 1.12.145 has requirement urllib3<1.25,>=1.20; python_version == "2.7", but you'll have urllib3 1.25.2 which is incompatible.
ERROR: openshift 0.8.8 has requirement kubernetes<9.0.0,>=8.0.0, but you'll have kubernetes 9.0.0 which is incompatible.
ERROR: openshift 0.8.8 has requirement urllib3<1.25, but you'll have urllib3 1.25.2 which is incompatible.
ERROR: python-solumclient 2.8.0 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.
ERROR: python-zaqarclient 1.11.0 has requirement jsonschema<3.0.0,>=2.6.0, but you'll have jsonschema 3.0.1 which is incompatible.

I tried changing global-constraints to resolve these conflicts, which was then successful. Do you have any insight into what needs to be changed with the keyring package?

My simple test was setting up virtualenv and running "./venv/bin/pip install -r global-requirements.txt".

Patch-set: 2
Reviewer: Gerrit User 17363 <17363@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Verified=0