Update patch set 1
Patch Set 1:

I have to say that I meet this problem again on a new centos vm.
My linux kernel version is 3.10.0-514.el7.x86_64, the python is 2.7.5.
The log of devstack show that problem when it installed psutil 5.4.6. The setuptools is 39.2.0 and the pip is 9.0.3. 
The error log is showen as below:
2018-06-27 09:58:47.194 | Collecting psutil===5.4.6 (from -c /opt/stack/requirements/upper-constraints.txt (line 321))
2018-06-27 09:58:49.827 |   Downloading https://files.pythonhosted.org/packages/51/9e/0f8f5423ce28c9109807024f7bdde776ed0b1161de20b408875de7e030c3/psutil-5.4.6.tar.gz (418kB)
2018-06-27 09:58:51.448 |     Complete output from command python setup.py egg_info:
2018-06-27 09:58:51.448 |     Traceback (most recent call last):
2018-06-27 09:58:51.448 |       File "<string>", line 1, in <module>
2018-06-27 09:58:51.448 |       File "/tmp/pip-build-SSYVbc/psutil/setup.py", line 351, in <module>
2018-06-27 09:58:51.448 |         main()
2018-06-27 09:58:51.448 |       File "/tmp/pip-build-SSYVbc/psutil/setup.py", line 347, in main
2018-06-27 09:58:51.448 |         setup(**kwargs)
2018-06-27 09:58:51.448 |       File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
2018-06-27 09:58:51.448 |         _setup_distribution = dist = klass(attrs)
2018-06-27 09:58:51.448 |       File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
2018-06-27 09:58:51.448 |         _Distribution.__init__(self,attrs)
2018-06-27 09:58:51.448 |       File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
2018-06-27 09:58:51.448 |         self.finalize_options()
2018-06-27 09:58:51.448 |       File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
2018-06-27 09:58:51.448 |         ep.load()(self, ep.name, value)
2018-06-27 09:58:51.449 |       File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
2018-06-27 09:58:51.449 |         return self.resolve()
2018-06-27 09:58:51.449 |       File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2239, in resolve
2018-06-27 09:58:51.449 |         raise ImportError(str(exc))
2018-06-27 09:58:51.449 |     ImportError: 'module' object has no attribute 'check_specifier'
2018-06-27 09:58:51.449 |
2018-06-27 09:58:51.449 |     ----------------------------------------
2018-06-27 09:58:51.601 | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SSYVbc/psutil/
2018-06-27 09:58:51.953 | You are using pip version 9.0.3, however version 10.0.1 is available.

When that problem occurs. I have to change the global-requirements.txt to refuse setuptools 39.2.0. Because I can't specify the setuptools version manually. The devstack will change it. It is really inconvenient.

Patch-set: 1