Update patch set 2
Patch Set 2:

(2 comments)

i'm just curious, but what does -2 mean in requirements. i take it to mean "don't want, give up" but then i realise i'm trying to help you fix a gate that is clearly broken. 

as i mentioned in previous reply, as i see it, i either upper cap docutils or i do this which i believe should've been done along with original patch.

regarding numpy, i want it removed because i'm not sure it ever should be in there. it's been there since beginning of 'requirements' but it's never listed in g-r. also, pandas and numpy are usually hand in hand and pandas is not in g-r or u-c. as there is no fake upper cap for pandas if you install pandas>=0.21.0 and you match this u-c of numpy==1.12.0 you get:

>>> import pandas
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

you can see it in ocata gate or just install the libs i just mentioned and try it yourself: http://logs.openstack.org/98/518098/2/check/telemetry-dsvm-integration-ceilometer/6d63471/logs/devstacklog.txt.gz

Patch-set: 2