No-python3 classifier for python-memcached
python-memcached doesn't support py34. keystonemiddleware py34 unit
tests fail with an error using python-memcached:

...
  File "/opt/stack/keystonemiddleware/.tox/py34/lib/python3.4/site-packages/memcache.py", line 1299, in send_cmd
    self.socket.sendall(cmd + '\r\n')
TypeError: 'str' does not support the buffer interface

Change-Id: Ie3dacedc9a355be914fe30f16dc40c58f779c46b