Rollback dulwich to 0.19.2
We need to have 0.19.2 until 0.19.4 is
released, the error problem is explained in [1].
Avoid unicode characters (e.g. the digraph ĳ in my surname) in setup.cfg,
+    since setuptools doesn't deal well with them. See
+    https://github.com/pypa/setuptools/issues/1062. (Jelmer Vernooĳ, #637)

dulwich 0.18.3 breaks in instack-undercloud with:

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ph6c_nsn/dulwich/setup.py", line 96, in <module>
        **setup_kwargs
      File "/repos/instack-undercloud/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/repos/instack-undercloud/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/repos/instack-undercloud/.tox/py36/lib/python3.6/site-packages/setuptools/dist.py", line 492, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/usr/lib64/python3.6/distutils/dist.py", line 395, in parse_config_files
        parser.read(filename)
      File "/usr/lib64/python3.6/configparser.py", line 697, in read
        self._read(fp, filename)
      File "/usr/lib64/python3.6/configparser.py", line 1015, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/repos/instack-undercloud/.tox/py36/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 48: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ph6c_nsn/dulwich/

[1]: https://github.com/dulwich/dulwich/commit/1b6509fa3dbd05c458990b71fadff91af095f733

Change-Id: Icabb56b9c6b2d99d78a7e1a77f8fe7a4ea6fa0c8