Update patch set 1
Patch Set 1:

hmm, seem to be a few mock issues (glance/ironic/nova), odd since we are not updating mock here

File "/home/zuul/src/opendev.org/openstack/glance/glance/tests/unit/test_cache_middleware.py", line 15, in <module>
    from mock import patch
ModuleNotFoundError: No module named 'mock'

ft1.1: nova.tests.unit.scheduler.test_filter_scheduler.FilterSchedulerTestCase.test_add_retry_hosttesttools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/zuul/src/opendev.org/openstack/nova/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1322, in patched
    arg = patching.__enter__()
  File "/home/zuul/src/opendev.org/openstack/nova/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1465, in __enter__
    "autospec creates the mock for you. Can't specify "
TypeError: autospec creates the mock for you. Can't specify autospec and new.

Patch-set: 1