Update patch set 1
Patch Set 1: I would prefer that you didn't merge this

Actually looks like zh_CN doesn't work with babel 1.1, so really we should be updating to 1.3.  I get this when compiling against babel 1.1:

babel.core.UnknownLocaleError: unknown locale 'zh_CN'

The release notes for babel also point out a fix for zh_CN in 1.3:

http://babel.pocoo.org/docs/changelog/#version-1-3

Patch-set: 1
Label: Code-Review=-1