Add mysqlclient as a MySQL-python replacement
mysqlclient is a fork of MySQLdb1 that adds Python 3 support and bug fixes.
They hope that it will be merged back to MySQLdb1.

This fixes the following error:
...
Collecting MySQL-python (from molteniron==0.0.1.dev14)
...
      File "/tmp/pip-build-oxdawap4/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
...

[Q] Is the library actively maintained?
[A] Yes. There have been 68 releases with the latest 27 days ago.

[Q] Is the library good code?
[A] It supports both 2.7 and 3.5 and also directly replaces MySQL-python.

[Q] Is the library python 3 compatible?
[A] Yes. It was a founding reason.

[Q] Is the library license compatible?
[A] Yes. GPLv2.

[Q] Is the library already packaged in the distros we target
    (Ubuntu latest / Fedora latest)?
[A] No.

[Q] Is the function of this library already covered by other
    libraries in global-requirements.txt?
[A] No.

[Q] Is the library required for OpenStack project or related dev
    or infrastructure setup? (Answer to this should be Yes,
    of course) Which?
[A] Yes. openstack/molteniron needs it as well as any other package
    using MySQL-python and hoping to switch to 3.5.

Change-Id: I0c1eafe8f8eb591d4928b4c0ed68cf2adc2eb7f5