Raise minimum pbr requirement: support env markers
In neutron, commit 2bbfe6f8253659ebf6951b6426ffc446baacd420 added lines
with "environment markers"[1][2] to requirements.txt:

pywin32;sys_platform=='win32'
wmi;sys_platform=='win32'

pbr started supporting this syntax at version 1.0.0, but the neutron
and global requirements files list a minimum version of 0.11:

pbr<2.0,>=0.11

This can cause fresh installations of a project using this syntax - e.g.
neutron - to fail with e.g.:

RequirementParseError: Expected version spec in
pywin32;sys_platform=='win32' at ;sys_platform=='win32'

...if setup happens to grab that minimum version.  This change set bumps
the minimum pbr version to 1.0.0 to prevent this error.

[1] http://docs.openstack.org/developer/pbr/#environment-markers
[2] https://www.python.org/dev/peps/pep-0426/#environment-markers

Change-Id: I5f57f72974721bce4b21eeb5db4b1a0abf600b33
Closes-Bug: #1471891