add openstack_requirements to sys.path in update.py
previously, when execute python update.py, no module error would occured,
because we import some module from parent directory of update.py.

Traceback (most recent call last):
  File "update.py", line 35, in <module>
    from openstack_requirements import project
ImportError: No module named openstack_requirements

Change-Id: I603967e3b700cd8ff44089d890e645de964b3806