Update patch set 2
Patch Set 2: Code-Review-1

Library is not python3 compatible:

 balder:ofpstr tony8129$ .venv/bin/python setup.py test
 running test
 running egg_info
 creating ofpstr.egg-info
 writing ofpstr.egg-info/PKG-INFO
 writing dependency_links to ofpstr.egg-info/dependency_links.txt
 writing entry points to ofpstr.egg-info/entry_points.txt
 writing top-level names to ofpstr.egg-info/top_level.txt
 writing manifest file 'ofpstr.egg-info/SOURCES.txt'
 reading manifest file 'ofpstr.egg-info/SOURCES.txt'
 writing manifest file 'ofpstr.egg-info/SOURCES.txt'
 running build_ext
 Traceback (most recent call last):
 <snip>
   File "/Users/tony8129/projects/openstack/related-projects/ofpstr/ofpstr/cli.py", line 56
     print ofp4.mpflow2text(msg)
              ^
 SyntaxError: invalid syntax

A better fix is incorporating the missing functionality into ryu and depending on that version

Patch-set: 2
Reviewer: Gerrit User 12898 <12898@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=-1