Revert "update constraint for oslo.service to new release 2.4.0"
Many jobs using upper-constraints file are failing installing
oslo.service version 2.4.0

 ERROR: Could not find a version that satisfies the requirement oslo.service===2.4.0 (from -r /home/zuul/src/opendev.org/openstack/requirements/upper-constraints.txt (line 36)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.16.1, 1.17.0, 1.18.0, 1.19.0, 1.19.1, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.24.1, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.27.0, 1.28.0, 1.28.1, 1.29.0, 1.29.1, 1.30.0, 1.31.0, 1.31.1, 1.31.2, 1.31.3, 1.31.4, 1.31.5, 1.31.6, 1.31.7, 1.31.8, 1.32.0, 1.32.1, 1.33.0, 1.34.0, 1.35.0, 1.36.0, 1.37.0, 1.38.0, 1.38.1, 1.39.0, 1.40.0, 1.40.1, 1.40.2, 1.41.0, 1.41.1, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.3.0, 2.3.1, 2.3.2)
 ERROR: No matching distribution found for oslo.service===2.4.0 (from -r /home/zuul/src/opendev.org/openstack/requirements/upper-constraints.txt (line 36))

This temporarly reverts commit 610e262079eadd34de4c7b0f725216f5256ed8e3
so that such jobs stop failing.

Change-Id: If49b13847337480552da47e2209a6c520c396e68