Update patch set 1
Patch Set 1:

Looks like nova unit tests are failing with error:

 ImportError: No module named _ThreadingEvent

because of mock.patching oslo_service.loopingcall._ThreadingEvent such as this:

https://github.com/openstack/nova/blob/536acbfe0572f10ea84f330f2f29b07ca9279114/nova/tests/unit/virt/disk/mount/test_api.py#L32

Patch-set: 1