ImportError: No module named vine.five
In Networking-vSphere py27 is failing because of ImportError.

vine.five is defined in kombu<4.0.0 version.
Hence patch https://review.openstack.org/#/c/411774 pushes to use
kombu<4.0.0 but global-requirement is not allowing to do that.

Change-Id: I6d629b2964c2541d47dc9b24fd3595a642f9a2b5