Update patch set 2
Patch Set 2:

Hey Matthew!

pydotplus didn't pull-in/provide the pydot library I guess:

  File "/Users/mkovacik/src/os/ironic-inspector/.tox/genstates/lib/python3.6/site-packages/automaton/converters/pydot.py", line 61, in convert 
    raise RuntimeError("pydot (or pydot2 or equivalent) is required"
  RuntimeError: pydot (or pydot2 or equivalent) is required to convert a state machine into a pydot graph

Also pydotplus doesn't seem as vital[1] as pydot3.

Cheers,
milan

[1] https://github.com/carlos-jenkins/pydotplus/commits/master

Patch-set: 2