WIP test cryptograhy 1.3.1 update
Testing theory, I got unclean local report this breaks nova-api with
the following backtrace:

 systemd[1]: Starting OpenStack Nova API Server...
 nova-api[26926]: Traceback (most recent call last):
 nova-api[26926]: File "/usr/bin/nova-api", line 6, in <module>
 nova-api[26926]: from nova.cmd.api import main
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/cmd/api.py", line 31, in <module>
 nova-api[26926]: from nova import service
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/service.py", line 32, in <module>
 nova-api[26926]: from nova import conductor
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/conductor/__init__.py", line 16, in <module>
 nova-api[26926]: from nova.conductor import api as conductor_api
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/conductor/api.py", line 22, in <module>
 nova-api[26926]: from nova.conductor import manager
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/conductor/manager.py", line 27, in <module>
 nova-api[26926]: from nova.compute import utils as compute_utils
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/compute/utils.py", line 32, in <module>
 nova-api[26926]: from nova import notifications
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/notifications.py", line 33, in <module>
 nova-api[26926]: from nova.image import glance
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 46, in <module>
 nova-api[26926]: from nova import signature_utils
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/nova/signature_utils.py", line 172, in <module>
 nova-api[26926]: if default_backend().elliptic_curve_supported(curve):
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/cryptography-1.3.1-py2.7-linux-x86_64.egg/cryptograp
 nova-api[26926]: _default_backend = MultiBackend(_available_backends())
 nova-api[26926]: File "/usr/lib/python2.7/site-packages/cryptography-1.3.1-py2.7-linux-x86_64.egg/cryptograp
 nova-api[26926]: "cryptography.backends"
 nova-api[26926]: AttributeError: 'EntryPoint' object has no attribute 'resolve'

Change-Id: I800c301e11fdd22b63af66b4f15973de7b5cba0d