Update patch set 3
Patch Set 3: Code-Review-1

I installed keyring 3.8 ,I don't think the patch can fix this issue.

  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
taget@taget-ThinkCentre-M58p:~/code/devstack$ keyrin^C
taget@taget-ThinkCentre-M58p:~/code/devstack$ pip show keyring
---
Name: keyring
Version: 3.8
Location: /usr/local/lib/python2.7/dist-packages
Requires:

Patch-set: 3
Reviewer: Gerrit User 12175 <12175@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=-1