Update patch set 2
Patch Set 2:

http://logs.openstack.org/88/235588/2/check/gate-requirements-integration-dsvm/dc9f6e4/console.html#_2015-10-16_05_16_52_604

Shows:
 ValueError: git history requires a target version of pbr.version.SemanticVersion(5.0.1), but target version is pbr.version.SemanticVersion(5.0.0)

So I think we're blocked on: https://bugs.launchpad.net/oslo.messaging/+bug/1505730

Patch-set: 2