Update patch set 1
Patch Set 1:

Looks like maybe we need to update this job to use py3?

From numpy:
RuntimeError: Python version >= 3.5 required.

https://github.com/numpy/numpy/commit/badf2901ea040aa89dbb3c19e53c6b1b692cb489

https://github.com/numpy/numpy/releases/tag/v1.17.0
"note that Python 2.7 has been dropped."

Patch-set: 1