Remove "args[0]" before trying to rename the file
On Windows, running edit-constraints.exe results in

Traceback (most recent call last):
  File "C:\Python27\Scripts\edit-constraints-script.py", line 9, in
<module>
    load_entry_point('openstack.requirements==0.0.1.dev2497',
'console_scripts', 'edit-constraints')()
  File
"C:\Python27\lib\site-packages\openstack_requirements\cmds\edit_constraint.py",
line 74, in main
    os.rename(args[0] + '.tmp', args[0])
WindowsError: [Error 183] Cannot create a file when that file already
exists

because the previous file was never deleted. This could be easily solved
by removing the file before the rename.

Proposed fix: Add before "os.rename(args[0] + '.tmp', args[0])" the
    line: "os.remove(args[0])"

Change-Id: If123a65fd8d49d5c67a1db16827a9617ce520dba