Use venv instead of virtualenv in generate script
The gate nodes no longer have the virtualenv package globally installed
and available, resulting in our nightly job failing with the error:

FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv'

To get around this, this patch updates our generate.py code to use the
venv module that is part of the standard lib in Python 3.3 and later.

Change-Id: I128ce15a1b6ce885dacae4ecd160f5892215683b
Signed-off-by: Sean McGinnis <sean.mcginnis@gmail.com>