Tox fails to build environment because of MySQL-Python version
  During tox building environment, it try to install the package
MySQL-python version 1.2.4 but the build failed with the error:

Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/opt/stack/nova/.tox/py27/build/MySQL-python/setup.py", line 18, in <module>
    metadata, options = get_config()
  File "setup_posix.py", line 43, in get_config
    libs = mysql_config("libs_r")
  File "setup_posix.py", line 25, in mysql_config
    raise EnvironmentError("%s not found" % (mysql_config.path,))
EnvironmentError: mysql_config not found

This patch fix the version at 1.2.3
The nova review: https://review.openstack.org/#/c/61955/

Change-Id: Id9e0afacee40adf101d40d076e1f5443b56523d1