Pin Sphinx to <1.2
1.2 was just released and has a bug that causes builds to fail with
the error:

  error: 'source_dir' must be a directory name (got `...doc/source`)

Change-Id: I0487b4eca8f2755b882689289e3cdf429729b1fb