update warlock due to bug on 1.3.1
UnicodeDecodeError: 'ascii' codec can't decode

Closes-Bug: #1829939
Change-Id: I4a2fc2030d12feb1eee29a5c826e20627b0540d4