Update patch set 2
Patch Set 2: Workflow-1

Yup:

https://8f7ecd6c133f5945c44f-888e5d5194de3968ae2aa6fe2799c1a7.ssl.cf2.rackcdn.com/679295/2/check/cross-cinder-py27/a6fbb6d/testr_results.html.gz

ft1.2: cinder.tests.unit.compute.test_nova.NovaClientTestCase.test_novaclient_exceptions_StringException: pythonlogging:'': {{{
2019-09-02 21:56:21,522 INFO [keystonemiddleware.auth_token] Starting Keystone auth_token middleware
2019-09-02 21:56:21,526 WARNING [keystonemiddleware._common.config] The option "auth_url" is not known to keystonemiddleware
2019-09-02 21:56:21,527 WARNING [keystonemiddleware.auth_token] AuthToken middleware is set with keystone_authtoken.service_token_roles_required set to False. This is backwards compatible but deprecated behaviour. Please set this to True.
2019-09-02 21:56:21,531 WARNING [keystonemiddleware.auth_token] Configuring www_authenticate_uri to point to the public identity endpoint is required; clients may not be able to authenticate against an admin endpoint
}}}

Traceback (most recent call last):
  File "cinder/tests/unit/compute/test_nova.py", line 178, in test_novaclient_exceptions
    self.assertTrue(hasattr(nova_exceptions, 'EndpointNotFound'))
  File "cinder/test.py", line 442, in assertTrue
    self.assertIs(True, x, *args, **kwargs)
  File "/home/zuul/src/opendev.org/openstack/cinder/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 445, in assertIs
    self.assertThat(observed, matcher, message)
  File "/home/zuul/src/opendev.org/openstack/cinder/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: False is not True

https://github.com/openstack/python-novaclient/commit/81ec72ecf8c32b409afedc60e013f9b4c47d5bae#diff-2ec4a4c853e7685ad4334b670e126c3cL73

Will fix Cinder.

Patch-set: 2
Reviewer: Gerrit User 6873 <6873@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Workflow=-1