Revert "update constraint for oslo.serialization to new release 2.21.2"
The update to 2.21.1 breaks glance unit tests:

FAIL: glance.tests.unit.v1.test_registry_api.TestRegistryAPI.test_update_all_image_members
----------------------------------------------------------------------
Traceback (most recent call last):
  File "glance/tests/unit/v1/test_registry_api.py", line 1629, in test_update_all_image_members
    content_type='json')
  File "glance/tests/utils.py", line 564, in get_api_response_ext
    self.assertEqual(res.status_int, http_resp)
  File "/data/dmueller/src/Cloud/glance/.tox/venv/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/data/dmueller/src/Cloud/glance/.tox/venv/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 200 != 204

Related-Bug: #1728368

This reverts commit 47206e21375ddd6a33c4b1e5d65d95976a73d70a.

Change-Id: Ic91acb78452ec5f73015b47bbb3effd0d6bda497