Update patch set 1
Patch Set 1:

Should this be reverted to <=0.7.9999999 ?

SQLAlchemy==0.8.0b2 is still available from https://pypi.python.org/packages/source/S/SQLAlchemy/ and <0.8 picks it up: http://logs.openstack.org/55/45555/7/check/gate-keystone-python27/fac64cc/console.html.gz

and breaks sqlalchemy-migrate:

...lib/python2.7/site-packages/migrate/versioning/schema.py", line 10, in <module>
|     from sqlalchemy import exceptions as sa_exceptions
| ImportError: cannot import name exceptions

Patch-set: 1