Update patch set 2
Patch Set 2:

> I don't believe this will break them, but they need to change that
 > anyway, so this is required to be able to do that. Direct git URLs
 > should not be used in requirements files.

[0] was an example of the breakage, the error message there:

ERROR: Could not satisfy constraints for 'neutron': installation from path or url cannot be constrained to a version

Furthermore every(?) networking-* and neutron-* project have 'dev' tox target for local runs of tests which uses the line:

pip install -q -e "git+https://git.openstack.org/openstack/neutron@stable/stein#egg=neutron"

This will also fail with the above error if I'm not mistaken. I'm ok with introducing this change but that will involve some other changes I think.

Patch-set: 2