Upgrade pyzmq to 25.0.0
``pyzmq 20.0.0`` has an issue in its packages, which makes it
impossible to install via ``pip``.

To reproduce the problem one can do the following (via install
from sources):
```
wget https://files.pythonhosted.org/packages/15/81/009a2cd08bc5de6ed092c94508b45d6dbc6f6d0bbeddbe14d36b51f28216/pyzmq-20.0.0.tar.gz

tar -xf pyzmq-20.0.0.tar.gz

cd pyzmq-20.0.0.tar.gz

pip install .

```

The error that will happen is the following:
```
Processing /pyzmq-20.0.0
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]

              It is possible a package already installed in your system
              contains an version that is invalid according to PEP 440.
              You can try `pip install --use-pep517` as a workaround for this problem,
              or rely on a new virtual environment.

              If the problem refers to a package that is not installed yet,
              please contact that package's maintainers or distributors.

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/pyzmq-20.0.0/setup.py", line 1378, in <module>
          setup(**setup_args)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/setuptools/dist.py", line 879, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 812, in resolve
          if not req_extras.markers_pass(req, extras):
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1016, in markers_pass
          return not req.marker or any(extra_evals)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1013, in <genexpr>
          req.marker.evaluate({'extra': extra})
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/markers.py", line 245, in evaluate
          return _evaluate_markers(self._markers, current_environment)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/markers.py", line 151, in _evaluate_markers
          groups[-1].append(_eval_op(lhs_value, op, rhs_value))
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/markers.py", line 109, in _eval_op
          return spec.contains(lhs, prereleases=True)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 565, in contains
          normalized_item = _coerce_version(item)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 36, in _coerce_version
          version = Version(version)
        File "/var/lib/kolla/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'cpython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

The same error happens when installing via ``pip`` and downloading from the
repository with ``pip install pyzmq===20.0.0``.

The error does not happen with either pyzmq<20 or pyzmq>20. This error
breaks Kolla build of containers, such as Neutron.

Ideally we need to propagate this change to stable branches as well.

Change-Id: Icb5eaec46dd187e5b9ccdfc2dbdf9f9ca7ef8c79