Tox fails to build environment because of MySQL-Python
  During tox building environment, it try to install the package
MySQL-python >=1.2.4 but the build failed with the error:

Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/opt/stack/nova/.tox/py27/build/MySQL-python/setup.py", line 18, in <module>
    metadata, options = get_config()
  File "setup_posix.py", line 43, in get_config
    libs = mysql_config("libs_r")
  File "setup_posix.py", line 25, in mysql_config
    raise EnvironmentError("%s not found" % (mysql_config.path,))
EnvironmentError: mysql_config not found

The package needs an external C library libmysqlclient

Change-Id: Iac1038f673efc035bca9ec703d6293c8cefae58c