require SQLAlchemy >=0.9.9
The GET v2/events/ call fails with "TypeError: get_bind() got
an unexpected keyword argument 'execution_options'".
The execution_options parameter that was added in SQLAlchemy 0.9.9.
However, ceilometer still requires >=0.9.7.

This change updates the requirement for  SQLAlchemy to be >=0.9.9.

Change-Id: Iaceabd0f1c5aac767dc446bd3be3035b972bd7b6
Closes-Bug: #1488117