Set jsonrpclib != 0.1.4
Version 0.1.4 of the jsonrpclib package came out today and is
uninstallable. Running pip wheel/install on this package results
in a stacktraced caused by a missing README.md file.

Traceback:
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-jUOSl3/jsonrpclib/setup.py", line 28, in <module>
        long_description = open("README.md").read()
    IOError: [Errno 2] No such file or directory: 'README.md'

The change is to simply skip this version.

Change-Id: I2d66bacdee433a2f7645ba8b396601c86513a218
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>