Pin kombu and amqp requirements due to incompatibility
kombu 5.0.2 bumped the amqp dependency from 2.6.1 to 5.0 but amqp 5.0
removed ca_certs ssl parameter from the connect call path. The
oslo.messaging still passes that parameter making nova fail if ssl is
configured for RPC.

Later amqp 5.0.2 reintroduced the ca_certs parameter but kolla now fails
with

ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED

To keep the resulting constraints consistent the vine constraint moved
back to 1.3.0 from 5.0.0

This patch partially reverts I1bc1fe988e3cfd4824dd7b4a9327a67db46c1533

Related-Bug: #1902696
Change-Id: Ic800d4f93cc324787fe22e27a25411e1565185d5