WIP: Fix compatibility with latest setuptools releases
With latest setuptools releases py3*-check-uc jobs started to fail
with error:

Traceback (most recent call last):
  File "/build-focal/.tox/py38-check-uc/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3030, in _dep_map
    return self.__dep_map
  File "/build-focal/.tox/py38-check-uc/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2826, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

The deliverables that produces the above errors are:
- virtualbmc
- salt
- pyzmq

A very old anyjson (latest release from 2012) has another compatibility
problem as it uses use_2to3 which is also not compatible with latest
setuptools.

Change-Id: I99c3fdf3481cb67b19815e86ac9f9ddd6d37fde0